# Импортиране на библиотека

In [ ]:
import numpy as np

# Зареждане на файл

In [142]:
file = np.loadtxt("SA_project/zad2.txt",dtype=int,  delimiter=",",) #вкарваме файла като матрица
ins = file[0:3]                                                     #извличаме cost редовете
zav = file[3]                                                       #извличаме supply
skl = file[4]                                                       #извличаме demand

# Принтиране на получените данни

In [139]:
print("Задачата е:")
print(ins)
print("Завод:",zav)
print("Склад:",skl)

Задачата е:
[[12 18  0]
 [15 24  0]
 [20 35  0]]
Завод: [1800 2600 2200]
Склад: [3000 2300 1300]


In [140]:
vs = 0; #крайна сума

# Изчисления по метода на СЗ ъгъл

In [143]:
for x in range(ins.shape[0]):
    for z in range(ins.shape[1]):

        minn = min(zav[x],skl[z])
        if (minn != 0):
            print("X",x+1,z+1,":",minn)
        if (minn != 0):
            vs = vs + minn * ins[x][z]
            print(ins[x][z],"*",minn)
        zav[x] -= minn
        skl[z] -= minn

X 1 1 : 1800
12 * 1800
X 2 1 : 1200
15 * 1200
X 2 2 : 1400
24 * 1400
X 3 2 : 900
35 * 900
X 3 3 : 1300
0 * 1300


# Крайна стойност за транспортната задача

In [135]:
print("Стойността за транспорт е",vs, "лв.")

Стойността за транспорт е 104700 лв.
